Food_management_system/Food_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from website import views
from food import views
#from .views import UserEditView
from django.contrib.auth import views as auth_views 
import doner

urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/', include('website.urls')),
    path('doner/',include('doner.urls')),
    path('food/',include('food.urls')),

]

Food_management_system/doner/mysite/food/urls.py
from django.urls import path

from . import views

app_name = 'food'

urlpatterns = [
    path('vfdetails', views.vfdetails, name="vfdetails"),
    path('vohistory', views.vohistory, name="vohistory"),
    path('pmanagement', views.pmanagement, name="pmanagement"),
    path('uploadf', views.uploadf, name="uploadf"),
    path('updatef', views.updatef, name="updatef"),
    path('fddetails', views.fddetails, name="fddetails"),
    path('ohistory', views.ohistory, name="ohistory"),
    path('confirmation', views.confirmation, name="confirmation"),

]

Food_management_system/doner/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('food/' , include('food.urls', namespace='food')),
]

Food_management_system/food/urls.py
from django.urls import path
from food import views

from . import views
from .views import RequestDonationView,RequestEditView,RequestDeleteView

app_name = 'food'

urlpatterns = [
    path('index1',views.index1,name="index1"),
    path('request_donation',RequestDonationView.as_view(),name='request-donation'),
    path('vfdetails/', views.vfdetails, name="vfdetails"),
    path('vohistory', views.vohistory, name="vohistory"),
    path('pmanagement', views.pmanagement, name="pmanagement"),
    path('order/<int:donation_id>/', views.order, name='order'),
    path('viewreq', views.viewreq, name="viewreq"),
    path('fddetails', views.fddetails, name="fddetails"),
    path('ohistory', views.ohistory, name="ohistory"),
    path('confirmation', views.confirmation, name="confirmation"),
    path('request-edit/<int:pk>',RequestEditView.as_view(),name="request-edit"),
    path('request-delete/<int:pk>',RequestDeleteView.as_view(),name='request-delete'),
    
    
    path('d_view_profile/',views.d_view_profile,name='d_view_profile'),
    path('d_edit_profile/', views.d_edit_profile, name='d_edit_profile'),

]

Food_management_system/doner/mysite/food/models.py
from django.db import models

# Create your models here.

Food_management_system/food/models.py
from django.db import models

class RequestDonation(models.Model):
    user=models.CharField(max_length=120)
    count = models.PositiveIntegerField()
    description = models.TextField()
    request_date = models.DateField()
    location = models.CharField(max_length=100)
    deadline = models.DateField()
    contact_information = models.CharField(max_length=100)

    def __str__(self):
        return self.user

class OrdersModel(models.Model):
    donor=models.CharField(max_length=120)
    donor_type=models.CharField(max_length=100)
    donor_discription=models.CharField(max_length=100)
    food_type=models.CharField(max_length=100)
    food=models.CharField(max_length=100)
    food_discription=models.CharField(max_length=100)
    date=models.DateTimeField()
    location=models.CharField(max_length=100)
    user=models.CharField(max_length=120)
    count = models.PositiveIntegerField()
    description = models.TextField()
    contact_information = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user

Food_management_system/food/forms.py
from django import forms
from .models import RequestDonation,OrdersModel
class RequestDonationForm(forms.ModelForm):
    class Meta:
        model = RequestDonation
        fields = "__all__"
        labels = {
            'user': 'User',
            'count': 'Count',
            'description': 'Description',
            'request_date': 'Request Date',
            'location': 'Location',
            'deadline': 'Deadline',
            'contact_information': 'Contact Information',
        }
        widgets = {
            'user': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'User'}),
            'count': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Count'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            'request_date': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Request Date'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Location'}),
            'deadline': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Deadline'}),
            'contact_information': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Contact Information'}),
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model = OrdersModel
        fields = ['count', 'description', 'contact_information']
        widgets = {
            'count': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'required': True}),
            'contact_information': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
        }

Food_management_system/doner/mysite/food/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    ctx = {'name':'Food Management System'}
    return render(request, 'food/index.html',ctx)

def vfdetails(request):
    return render(request, 'food/vfdetails.html')

def vohistory(request):
    return render(request, 'food/vohistory.html')

def pmanagement(request):
    return render(request, 'food/pmanagement.html')

def uploadf(request):
    return render(request, 'food/uploadf.html')

def updatef(request):
    return render(request, 'food/updatef.html')

def fddetails(request):
    return render(request, 'food/fddetails.html')

def ohistory(request):
    return render(request, 'food/ohistory.html')

def confirmation(request):
    return render(request, 'food/confirmation.html')

Food_management_system/food/views.py
from django.shortcuts import render, redirect
from .forms import RequestDonationForm,OrderForm
from .models import RequestDonation, OrdersModel
from doner.models import DonateFoodModel
from django.views.generic import TemplateView
from django.utils import timezone
from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required
from website.models import Profile
from django.contrib import messages

from website.models import Profile
from django.urls import reverse

from django.urls import reverse_lazy
from django.urls import reverse
from django.contrib.auth.models import User


@login_required(login_url='login')
def index1(request):
    return render(request, "food/index1.html", {})


@login_required(login_url='login')
def d_view_profile(request):
  if request.method == 'POST':
    return redirect(reverse('food:d_view_profile'))

  return render(request, 'food/d_view_profile.html')


@login_required
def d_edit_profile(request):
    if request.method == 'POST':
        # Get the data that the user submitted from the form.
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        mobile = request.POST.get('mobile')
        user_type = request.POST.get('user_type')
        

        # Check if the new email is already in use by another user.
        if User.objects.exclude(id=request.user.id).filter(email=email).exists():
            error_message = f"The email id {email} is already used by another user. Please choose another."
            messages.add_message(request, messages.ERROR, error_message)

        # Check if the new mobile number is already in use by another user.
        if Profile.objects.exclude(user=request.user).filter(mobile=mobile).exists():
            messages.add_message(request, messages.ERROR, f"The mobile number '{mobile}' is already in use by another user. Please choose another.")

        # If there are any error messages, redirect to the edit profile page.
        if messages.get_messages(request):
            return redirect('d_edit_profile')
        
        # Update the user's profile details in the database.
        my_user = request.user
        my_user.first_name = first_name
        my_user.last_name = last_name
        my_user.email = email
        my_user.username=email
        my_user.save()

        profile = Profile.objects.get(user=my_user)
        profile.mobile = mobile
        profile.user_type = user_type
        profile.save()

        # Redirect the user to the profile page.
        return redirect('d_view_profile')

    else:
        # If the request method is not POST, render the edit profile page.
        return render(request, 'food/d_edit_profile.html')



@method_decorator(login_required, name='dispatch')
class RequestDonationView(TemplateView):
    form_class = RequestDonationForm
    model = RequestDonation
    template_name = "food/request_donation.html"
    context = {}

    def get(self, request, *args, **kwargs):
        today = timezone.localdate()
        form = self.form_class(initial={"user": request.user, "request_date": today})
        self.context["form"] = form
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect("food:index1")
        return render(request, self.template_name, self.context)


class RequestEditView(TemplateView):
    model = RequestDonation
    form_class = RequestDonationForm
    template_name = "food/request_donation.html"
    context = {}

    def get(self, request, *args, **kwargs):
        edit = self.model.objects.get(id=kwargs["pk"])
        form = self.form_class(instance=edit)
        self.context["form"] = form
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        edit = self.model.objects.get(id=kwargs["pk"])
        form = self.form_class(request.POST, instance=edit)
        if form.is_valid():
            form.save()
            return redirect("food:viewreq")
        else:
            return render(request, self.template_name, self.context)


class RequestDeleteView(TemplateView):
    model = RequestDonation

    def get(self, request, *args, **kwargs):
        item = self.model.objects.get(id=kwargs["pk"])
        item.delete()
        return redirect("food:viewreq")


def vfdetails(request):
    donations = DonateFoodModel.objects.all()
    context = {'donations': donations}
    return render(request, 'food/vfdetails.html', context)


def vohistory(request):
    orders = OrdersModel.objects.filter(user=request.user)
    context = {
        'orders': orders
    }
    return render(request, 'food/vohistory.html', context)

def pmanagement(request):
    return render(request, 'food/pmanagement.html')


from .forms import OrderForm

def order(request, donation_id):
    donation = DonateFoodModel.objects.get(id=donation_id)
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.donor = donation.user
            order.donor_type = donation.donor_type
            order.donor_discription = donation.donor_discription
            order.food_type = donation.food_type
            order.food = donation.food
            order.food_discription = donation.food_discription
            order.date = donation.date
            order.location = donation.location
            order.user = request.user
            order.save()
            # Additional processing code for the created order
            return redirect("food:confirmation")
    else:
        form = OrderForm()
    context = {
        'form': form,
        'donation': donation
    }
    return render(request, 'food/order.html', context)



def viewreq(request):
    requested_donations = RequestDonation.objects.filter(user=request.user)
    context = {'requested_donations': requested_donations}
    return render(request, 'food/viewreq.html', context)


def fddetails(request):
    return render(request, 'food/fddetails.html')


def ohistory(request):
    return render(request, 'food/ohistory.html')


def confirmation(request):
    return render(request, 'food/confirmation.html')

Food_management_system/food/templates/food/base.html
<!DOCTYPE html>
{%load static%}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>NO MORE HUNGER</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'food/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'food/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'food/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'food/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'food/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'food/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'food/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'food/assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NewBiz
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/newbiz-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo">
        <!-- Uncomment below if you prefer to use an text logo -->
        <!-- <h1><a href="index1.html">NewBiz</a></h1> -->
        <!-- <a href="home.html"><img src="{% static 'website/assets/img/logo.png'%}" alt="" class="img-fluid"></a> -->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          {% if request.resolver_match.app_name == 'doner' %}
          <li><a class="nav-link scrollto active" href="{% url 'doner:index1' %}">Home</a></li>
        {% elif request.resolver_match.app_name == 'food' %}
          <li><a class="nav-link scrollto active" href="{% url 'food:index1' %}">Home</a></li>
        {% endif %}
          <li><a class="nav-link scrollto" href="{% url 'food:vfdetails' %}">Order</a></li>
          <li><a class="nav-link scrollto" href="{% url 'food:viewreq' %}">Requested Donations</a></li>
          <!-- <li><a class="nav-link scrollto" href="#services">Services</a></li> -->
          <!-- <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li> -->
          <li><a class="nav-link scrollto" href="{% url 'food:d_view_profile' %}">Profile</a></li>
          <li><a class="nav-link scrollto" href="{% url 'food:vohistory' %}">Order history</a></li>
          <li><a class="nav-link scrollto " href="{% url 'feedback' %}">Feedbacks</a></li>
          <li><a class="nav-link scrollto" href="{% url 'logout' %}">Logout</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- #header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="clearfix">
    <div class="container" data-aos="fade-up">
    {%block body_block%}


    {%endblock%}
      

    </div>
  </section><!-- End Hero Section -->

  <main id="main">

    
  <!-- Vendor JS Files -->
  <script src="{% static 'food/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'food/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'food/assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'food/assets/vendor/glightbox/js/glightbox.min.js '%}"></script>
  <script src="{% static 'food/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'food/assets/vendor/swiper/swiper-bundle.min.js' %} "></script>
  <script src="{% static 'food/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'food/assets/js/main.js'%}"></script>


    
</body>

</html>

Food_management_system/food/templates/food/confirmation.html
{% extends 'food/base.html' %}

{% block body_block %}
<section id="confirmation-section" class="section">
  <div class="container text-center">
    <h2 class="section-title" style="font-weight: bold; color: white; margin-top: -6px; font-size: 40px;">Order Confirmed</h2>
    <p style="color: white; margin-top: 20px; font-size: 18px;">Thank you for your order!</p>
    <a href="{% url 'food:index1' %}" class="btn btn-primary mt-4">Click to return to home</a>
  </div>
</section>
{% endblock %}

Food_management_system/food/templates/food/d_edit_profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup Page</title>
    <link href="{% static 'website/css/style1.css' %}" rel="stylesheet">   
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>

{% block body_block %}
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-lg-5 col-md-7 offset-lg-4 offset-md-3">
      <div class="panel border bg-white">
        <div class="panel-heading">
          <h3 class="pt-3 font-weight-bold">Edit Profile</h3>
        </div>
        <div class="panel-body p-3">
          <form action="{% url 'food:d_view_profile' %}" method="post">
            {% csrf_token %} 

            <div class="row">
              <div class="col-md-12">
                {% if messages %}
                  <div class="alert alert-danger">
                    <ul>
                      {% for message in messages %}
                        <li style="color: red;">{{ message }}</li>
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
              </div>
            </div>
        
            <div class="form-group py-2">
              <label for="first_name" style="color:black">First Name:</label>
              <div class="input-field"><span class="far fa-user p-2"></span> <input type="text" placeholder="First Name" id="first_name" name="first_name" value="{{ user.first_name }}" class="form-control" required> </div>
            </div>
            <div class="form-group py-1">
              <label for="last_name" style="color:black">Last Name:</label>
              <div class="input-field"><span class="far fa-user p-2"></span> <input type="text" placeholder="Last Name" id="last_name" name="last_name" value="{{ user.last_name }}" class="form-control" required> </div>
            </div>
            <div class="form-group py-1">
              <label for="email" style="color:black">Email:</label>
              <div class="input-field"><span class="fas fa-envelope p-2"></span> <input type="text" placeholder="Email" id="email" name="email" value="{{ user.email }}" class="form-control" required> </div>
            </div>
            <div class="form-group py-1">
              <label for="mobile" style="color:black">Mobile:</label>
              <div class="input-field"><span class="fas fa-phone p-2"></span> <input type="text" placeholder="Mobile" id="mobile" name="mobile" pattern="[0-9]{10}" value="{{ user.profile.mobile }}" class="form-control" required> </div>
            </div>

            <div id="passwordError" style="display:none;color:red">Password and Confirm Password do not match</div>

            <script>
            function checkPassword() {
              var password1 = document.getElementById("password1").value;
              var password2 = document.getElementById("password2").value;
              if (password1 != password2) {
                document.getElementById("passwordError").style.display = "block";
              } else {
                document.getElementById("passwordError").style.display = "none";
              }
            }
            </script>

            <div class="row">
              <div class="col-md-8">
                <div class="form-group">
                  <label for="user_type" >User Type:</label>
                  <br>
                  <input type="radio" id="donor" name="user_type" value="donor" {% if user.profile.user_type == 'donor' %}checked{% endif %} required>
                  <label for="donor" >Donor</label>
                  <br>
                  <input type="radio" id="distributor" name="user_type" value="distributor" {% if user.profile.user_type == 'distributor' %}checked{% endif %} required>
                  <label for="distributor" >Distributor</label>
                  <br>
                </div>
              </div>
            </div>
            <button class="btn btn-primary btn-block mt-3" type="submit">Update Profile</button>
            <div class="text-center pt-4 text-muted">To go back  <a href="{% url 'food:d_view_profile' %}" >Click here</a> </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Food_management_system/food/templates/food/fddetails.html
{% extends 'food/base.html' %}


{% block title %}Order history{% endblock %}

{% block content %}

<h2>View food details here</h2>

{% endblock %}

Food_management_system/food/templates/food/index.html
<!DOCTYPE html>
{%extends 'food/base.html'%}

{%block body_block%}

  <div class="hero-info" data-aos="zoom-in" data-aos-delay="100">
    <h2>Welcome {{ user.first_name}} <br>If you would like to request donation, please click the Request Donation button below</h2>
    <div>
      <!-- <a href="#about" class="btn-get-started scrollto">Get Started</a> -->
      <a href="{% url 'food:request-donation'%}" class="btn-services scrollto">Request Donation</a>
    </div>
  </div>

{% endblock %}

Food_management_system/food/templates/food/index1.html
<!DOCTYPE html>
{%extends 'food/base.html'%}

{%block body_block%}

  <div class="hero-info" data-aos="zoom-in" data-aos-delay="100">
    <h2>Welcome {{ user.first_name}} <br>If you would like to request donation, please click the Request Donation button below</h2>
    <div>
      <!-- <a href="#about" class="btn-get-started scrollto">Get Started</a> -->
      <a href="{% url 'food:request-donation'%}" class="btn-services scrollto">Request Donation</a>
    </div>
  </div>

{% endblock %}

Food_management_system/food/templates/food/ohistory.html
{% extends 'food/base.html' %}


{% block title %}Order history{% endblock %}

{% block content %}

<h2>View order history here</h2>

{% endblock %}

Food_management_system/food/templates/food/order.html
{% extends 'food/base.html' %}

{% block body_block %}
  <h1 style="color: white; font-weight: bold;">Order Details</h1>
  <div class="order-details">
    <div class="donation-details">
      <h3 style="color: white;">Donation Details:</h3>
      <p><strong style="color: white;">Donor:</strong> <span style="color: #f6c23e;">{{ donation.user }}</span></p>
      <p><strong style="color: white;">Donor Type:</strong> <span style="color: #f6c23e;">{{ donation.donor_type }}</span></p>
      <p><strong style="color: white;">Donor Description:</strong> <span style="color: #f6c23e;">{{ donation.donor_discription }}</span></p>
      <p><strong style="color: white;">Food Type:</strong> <span style="color: #f6c23e;">{{ donation.food_type }}</span></p>
      <p><strong style="color: white;">Food:</strong> <span style="color: #f6c23e;">{{ donation.food }}</span></p>
      <p><strong style="color: white;">Food Description:</strong> <span style="color: #f6c23e;">{{ donation.food_discription }}</span></p>
      <p><strong style="color: white;">Date:</strong> <span style="color: #f6c23e;">{{ donation.date }}</span></p>
      <p><strong style="color: white;">Location:</strong> <span style="color: #f6c23e;">{{ donation.location }}</span></p>
    </div>
    <hr>
    <h3 style="color: white;">Additional Order Information:</h3>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="count" style="color: white;">Count:</label>
        <input type="number" id="count" name="count" class="form-control" required>
      </div>
      <div class="form-group">
        <label for="description" style="color: white;">Description:</label>
        <textarea id="description" name="description" class="form-control" required></textarea>
      </div>
      <div class="form-group">
        <label for="contact_information" style="color: white;">Contact Information:</label>
        <input type="text" id="contact_information" name="contact_information" class="form-control" required>
      </div>
      <div style="margin-top: 20px;">
        <input type="submit" value="Order" class="btn btn-primary">
      </div>
    </form>
  </div>
{% endblock %}

Food_management_system/food/templates/food/pmanagement.html
{% extends 'food/base.html' %}


{% block title %}Profile Management{% endblock %}

{% block content %}

<h2>Manage Your Profile Here</h2>

{% endblock %}

Food_management_system/food/templates/food/request_donation.html
<!DOCTYPE html>
{%extends 'food/base.html'%}

{%block body_block%}

<h1 id="donate-heading">Request Donation</h1>
<form action="" method="POST">{%csrf_token%}
    <div class="container ">
        <div class="row " id="donate-form">
            <div class="col-6 col-sm-3">
                <div class="label-gap">
                    <label for="user" class="dof-lab">Username</label>
                    {{form.user}}
                </div>
                <div class="label-gap">
                    <label for="count" class="dof-lab">Count</label>
                    {{form.count}}
                </div>
                <div class="label-gap">
                    <label for="description" class="dof-lab">Discription</label>
                    {{form.description}}
                </div>
                <div class="label-gap">
                    <label for="location" class="dof-lab">Location</label>
                    {{form.location}}
                </div>
            </div>
            <div class="col-6 col-sm-3" id="dofm-col2">
                <div class="label-gap">
                    <label for="request_date" class="dof-lab">Request Date</label>
                    {{form.request_date}}
                </div>
                <div class="label-gap">
                    <label for="deadline" class="dof-lab">Deadline</label>
                    {{form.deadline}}
                </div>
                <div class="label-gap">
                    <label for="contact_information" class="dof-lab">Contact Information</label>
                    {{form.contact_information}}
                </div>
                <div class="label-gap">
                    <label for="date" class="dof-lab">Date</label>
                    {{form.date}}
                </div>
            </div>
            <div class="label-gap">
      <input type="submit" id='donate-submit'value="submit">
            </div>
        </div>
    </div>

</form>
    {% endblock %}
    


     

Food_management_system/food/templates/food/uploadf.html
{% extends 'food/base.html' %}


{% block title %}Order history{% endblock %}

{% block content %}

<h2>Upload food details here</h2>

{% endblock %}

Food_management_system/food/templates/food/vfdetails.html
{% extends 'food/base.html' %}

{% block body_block %}
<section id="donation-section" class="section">
  <div class="container">
    <h2 class="section-title" style="font-weight: bold; color: white; margin-top: -6px; font-size: 40px;">Available Donations</h2>
    <p style="color: white; margin-top: 20px; font-size: 16px;">Click on any donation to order</p>
    {% if donations %}
    <div class="row">
      {% for don in donations %}
      <div class="col-lg-4 col-md-6">
        <a href="{% url 'food:order' donation_id=don.id %}">
          <div class="card" style="background: linear-gradient(to bottom right, #00a8ff, #003f9e); border-radius: 5px; padding: 10px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);">
            <div class="card-header" style="background-color: transparent; border: none;">
              <h3 class="card-title" style="font-size: 18px; font-weight: bold; color: white; margin: 0;">{{ don.food_type }}</h3>
            </div>
            <div class="card-body">
              <p class="card-text" style="color: white;">Food description: {{ don.food_discription }}</p>
              <p class="card-text" style="color: white;">Donor: {{ don.user }}</p>
              <p class="card-text" style="color: white;">Donor Type: {{ don.donor_type }}</p>
              <p class="card-text" style="color: white;">Donor Description: {{ don.donor_discription }}</p>
              <p class="card-text" style="color: white;">Supply Date: {{ don.date }}</p>
              <p class="card-text" style="color: white;">Location: {{ don.location }}</p>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <p style="color: white;">No donations available.</p>
    {% endif %}
  </div>
</section>
{% endblock %}

Food_management_system/food/templates/food/viewreq.html
<!DOCTYPE html>
{% extends 'food/base.html' %}

{% block body_block %}

<h2 id="donation_history">Requested Donations</h2>

<div>
    <table class="table table-success table-striped">
        <tr>
            <th>User</th>
            <th>Count</th>
            <th>Description</th>
            <th>Request Date</th>
            <th>Deadline</th>
            <th>Contact Information</th>
            <th>Location</th>
            <th></th>
            <th></th>
        </tr>
        {% for donation in requested_donations %}
        <tr>
            <td>{{ donation.user }}</td>
            <td>{{ donation.count }}</td>
            <td>{{ donation.description }}</td>
            <td>{{ donation.request_date }}</td>
            <td>{{ donation.deadline }}</td>
            <td>{{ donation.contact_information }}</td>
            <td>{{ donation.location }}</td>
            <td><a href="{%url 'food:request-edit' donation.id%}" class="btn btn-success">Edit</a></td>
            <td> <a href="{%url 'food:request-delete' donation.id%}" class="btn btn-danger">Delete</a></td>
           
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}